deal:
  calculatorBaseUrl: http://localhost:8080
  calculatorOffersUrl: /calculator/offers
  calculatorCalcUrl: /calculator/calc
  kafka:
    topics:
      finish-registration: finish-registration
      create-documents: create-documents
      send-documents: send-documents
      ses-code: send-ses
      credit-issued: credit-issued
      statement-denied: statement-denied
  mail:
    text:
      finish-registration: Ваша заявка предварительно одобрена, завершите оформление
      create-documents: Кредит одобрен. Оформить документы http://localhost:8084/document/{statementId}
      send-documents: Ваши документы готовы. Подписать http://localhost:8084/document/{statementId}/sign
      ses-code: Подтвердите подписание документов http://localhost:8084/document/{statementId}/sign/code Код подтверждения {code}
      credit-issued: Кредит оформлен.
      wrong-ses-code: Неверный код
      statement-denied: Заявка на кредит отклонена

server:
  port: 8081

springdoc:
  swagger-ui:
    path: /swagger-ui

spring:
  datasource:
    url: jdbc:postgresql://resources-postgresql-1:5432/deal
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    change-log: classpath:/migrations/master.xml
  kafka:
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer