version: "1"

services:
  postgresql:
    image: postgres:15
    volumes:
      - postgres_data:/postgres_data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=deal
    ports:
      - 5433:5432
    restart: always

volumes:
  postgres_data: