gateway:
  statementClient:
    baseUrl: http://localhost:8082
    offerUrl: /statement/offer
    statementUrl: /statement
  dealClient:
    baseUrl: http://localhost:8081
    calculateUrl: /deal/calculate/{statementId}
    sendUrl: /deal/document/{statementId}/send
    signUrl: /deal/document/{statementId}/sign
    codeUrl: /deal/document/{statementId}/code

server:
  port: 8084

springdoc:
  swagger-ui:
    path: /swagger-ui